# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aura_pb2 as aura__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aura_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuraServiceStub(object):
    """==========================================
    Services
    ==========================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmpathy = channel.unary_unary(
                '/aura.AuraService/GenerateEmpathy',
                request_serializer=aura__pb2.ContextualPrompt.SerializeToString,
                response_deserializer=aura__pb2.EmpathyResponse.FromString,
                _registered_method=True)


class AuraServiceServicer(object):
    """==========================================
    Services
    ==========================================

    """

    def GenerateEmpathy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmpathy': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmpathy,
                    request_deserializer=aura__pb2.ContextualPrompt.FromString,
                    response_serializer=aura__pb2.EmpathyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.AuraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.AuraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuraService(object):
    """==========================================
    Services
    ==========================================

    """

    @staticmethod
    def GenerateEmpathy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.AuraService/GenerateEmpathy',
            aura__pb2.ContextualPrompt.SerializeToString,
            aura__pb2.EmpathyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuraPerceptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFacePerception = channel.unary_unary(
                '/aura.AuraPerception/SendFacePerception',
                request_serializer=aura__pb2.EmotionCandidate.SerializeToString,
                response_deserializer=aura__pb2.EmpathyResponse.FromString,
                _registered_method=True)
        self.SendVoicePerception = channel.unary_unary(
                '/aura.AuraPerception/SendVoicePerception',
                request_serializer=aura__pb2.EmotionCandidate.SerializeToString,
                response_deserializer=aura__pb2.EmpathyResponse.FromString,
                _registered_method=True)


class AuraPerceptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFacePerception(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVoicePerception(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuraPerceptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFacePerception': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFacePerception,
                    request_deserializer=aura__pb2.EmotionCandidate.FromString,
                    response_serializer=aura__pb2.EmpathyResponse.SerializeToString,
            ),
            'SendVoicePerception': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVoicePerception,
                    request_deserializer=aura__pb2.EmotionCandidate.FromString,
                    response_serializer=aura__pb2.EmpathyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.AuraPerception', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.AuraPerception', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuraPerception(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFacePerception(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.AuraPerception/SendFacePerception',
            aura__pb2.EmotionCandidate.SerializeToString,
            aura__pb2.EmpathyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendVoicePerception(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.AuraPerception/SendVoicePerception',
            aura__pb2.EmotionCandidate.SerializeToString,
            aura__pb2.EmpathyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuraTTSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDialogue = channel.unary_unary(
                '/aura.AuraTTS/SendDialogue',
                request_serializer=aura__pb2.TTSRequest.SerializeToString,
                response_deserializer=aura__pb2.EmpathyResponse.FromString,
                _registered_method=True)


class AuraTTSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDialogue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuraTTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDialogue': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDialogue,
                    request_deserializer=aura__pb2.TTSRequest.FromString,
                    response_serializer=aura__pb2.EmpathyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.AuraTTS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.AuraTTS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuraTTS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDialogue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.AuraTTS/SendDialogue',
            aura__pb2.TTSRequest.SerializeToString,
            aura__pb2.EmpathyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
